apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  camunda.com/team: distribution

commonLabels:
  app.kubernetes.io/managed-by: kustomize

namespace: external-dns

resources:
- ./secret.yaml
