apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  name: {{ include "webModeler.fullname" . }}
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  pusher-app-id: web-modeler
  pusher-app-key: {{ randAlphaNum 20 }}
