{{- if .Values.prometheusServiceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "camundaPlatform.fullname" . }}
  labels: {{- include "camundaPlatform.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.global.labels | nindent 6 }}
  endpoints:
    - honorLabels: true
      path: /actuator/prometheus
      port: http
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
    {{- if .Values.global.identity.auth.enabled }}
    - honorLabels: true
      path: /actuator/prometheus
      port: metrics
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
    {{- end }}
    {{- if .Values.optimize.enabled }}
    - honorLabels: true
      path: /actuator/prometheus
      port: management
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
    {{- end }}
{{- end }}
