apiVersion: v2
name: camunda-platform
version: 8.1.0
appVersion: "8.0.0"
description: |
  Camunda Platform 8 Self-Managed Helm charts.
  Camunda's process automation platform allows developers to design, automate and improve processes.
type: application
icon: https://helm.camunda.io/imgs/camunda.svg
home: https://docs.camunda.io/docs/self-managed/overview/
sources:
  - https://github.com/camunda/camunda-platform-helm
keywords:
  - bpm
  - bpmn
  - camunda-platform
  - dmn
  - process-engine
  - workflow
dependencies:
  # Camunda Platform charts.
  - name: identity
    version: 8.1.0
    condition: "identity.enabled"
  - name: operate
    version: 8.1.0
    condition: "operate.enabled"
  - name: optimize
    version: 8.1.0
    condition: "optimize.enabled"
  - name: tasklist
    version: 8.1.0
    condition: "tasklist.enabled"
  - name: zeebe
    version: 8.1.0
    condition: "zeebe.enabled"
  - name: zeebe-gateway
    version: 8.1.0
    condition: "zeebe.enabled"
  # Dependency charts.
  - name: elasticsearch
    repository: "https://helm.elastic.co"
    version: 7.17.1
    condition: "elasticsearch.enabled"
  # Helpers charts.
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
  - name: aabouzaid
    email: ahmed.abouzaid@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Camunda Platform 8 docs
      url: https://docs.camunda.io/
    - name: Camunda Platform 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda Platform 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: "set jwt tokens source for operate, optimize, and tasklist"
    - kind: added
      description: "config tasklist elasticsearch url"
    - kind: added
      description: "configure securityContext for pod and container"
    - kind: added
      description: "support single domain setup"
    - kind: fixed
      description: "remove identity/optimize vars when auth is disabled"
    - kind: fixed
      description: "operate logging level package name"
    - kind: fixed
      description: "unify sub-charts icon"
    - kind: fixed
      description: "unify imagePullPolicy across components"
