apiVersion: v2
name: camunda-platform
version: 10.0.0
appVersion: 8.5.x
description: |
  Camunda 8 Self-Managed Helm charts.
  Camunda's process automation platform allows developers to design, automate and improve processes.
type: application
icon: https://helm.camunda.io/imgs/camunda.svg
home: https://docs.camunda.io/docs/self-managed/overview/
sources:
  - https://github.com/camunda/camunda-platform-helm
keywords:
  - bpm
  - bpmn
  - camunda-platform
  - dmn
  - process-engine
  - workflow
dependencies:
  # Identity Dependencies.
  - name: keycloak
    alias: identityKeycloak
    repository: https://charts.bitnami.com/bitnami
    version: 19.4.1
    condition: "identityKeycloak.enabled"
  - name: postgresql
    alias: identityPostgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
    condition: "identityPostgresql.enabled"
  # WebModeler Dependencies.
  - name: web-modeler-postgresql
    alias: postgresql
    repository: "file://../web-modeler-postgresql"
    version: 11.x.x
    condition: "postgresql.enabled"
  # Shared Dependencies.
  - name: elasticsearch
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 20.0.0
    condition: "elasticsearch.enabled"
  # Helpers.
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
  - name: aabouzaid
    email: ahmed.abouzaid@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: "AWS IRSA Addition"
    - kind: added
      description: "override application config"
    - kind: added
      description: "external elasticsearch"
    - kind: added
      description: "support customizing ingress pathType"
    - kind: added
      description: "add zeebe gateway REST API"
    - kind: fixed
      description: "keycloak path defaults to having trailing /"
    - kind: fixed
      description: "broken helm upgrades due to matchLabels including image version tags"
    - kind: fixed
      description: "add camundaPlatform.imageTagByParams to component helpers.tpl"
    - kind: fixed
      description: "references to grpc:// protocol removed"
    - kind: fixed
      description: "defining resources and limits for optimize migration container"
    - kind: fixed
      description: "remove extra char in IDENTITY_URL"
    - kind: changed
      description: "adding zeebe rest config for tasklist"
    - kind: changed
      description: "upgrade keycloak from v22 to v23"
    - kind: changed
      description: "upgrade elasticsearch from 8.9 to 8.12"
    - kind: changed
      description: "rename zeebe-gateway key from to zeebeGateway"
    - kind: changed
      description: "rename web-modeler postgres key to webModelerPostgresql"
    - kind: changed
      description: "move identity and its dependencies to top-level"
    - kind: changed
      description: "use the unified uid/gid 1001 for all components"
