##
# This is a minimal sample values file to get you started with an Openshift cluster using the recommended default
# policies. Using these values, you will be able to deploy the chart using the least permissive SCC, "restricted".
##
---

#
# Elasticsearch.
#

# omit the values below if elasticsearch.enabled is false
elasticsearch:
  # If needed, OpenShift TuneD operator will be used to set sysctl vm.max_map_count.
  # Apply the manifest "openshift-tuned.yaml" before install Camunda 8 chart.
  sysctlImage:
    enabled: false
  commonLabels:
    tuned.openshift.io/elasticsearch: ""
