{{- if and .Values.externalDatabase.enabled (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity.postgresql.secretName" . }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "identity.postgresql.secretKey" . }}: {{ include "identity.postgresql.secretPassword" . | b64enc | quote }}
{{- end }}
