{{- if or .Values.postgresql.enabled .Values.externalDatabase.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.postgresql.id" . }}
  labels: {{- include "identity.labels" . | nindent 4 }}
  annotations: {{- toYaml  .Values.global.annotations | nindent 4 }}
data:
  MULTITENANCY_ENABLED: {{ .Values.global.multitenancy.enabled | quote }}
  IDENTITY_DATABASE_HOST: {{ include "identity.postgresql.host" . | quote }}
  IDENTITY_DATABASE_PORT: {{ include "identity.postgresql.port" . | quote }}
  IDENTITY_DATABASE_NAME: {{ include "identity.postgresql.database" . | quote }}
  IDENTITY_DATABASE_USERNAME: {{ include "identity.postgresql.username" . | quote }}
{{- end }}
