{{- if .Values.global.identity.auth.enabled }}
{{- if and (not .Values.postgresql.enabled) (typeIs "string" .Values.global.identity.externalDatabase.auth.password) }}
{{- $secretName := include "identity.postgresql.databaseSecretName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{- include "identity.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "identity.postgresql.databaseSecretKey"}}: {{ .Values.global.identity.externalDatabase.auth.password | b64enc }}
{{- end }}
{{- end }}