apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-camunda-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: distribution-team
  target:
    name: camunda-platform  # name of the k8s Secret to be created
  data:
  - secretKey: tls.crt
    remoteRef:
      key: ci-distro-ultrawombat-com
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: ci-distro-ultrawombat-com
      property: tls.key

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-zeebe-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: distribution-team
  target:
    name: camunda-platform-zeebe-gateway  # name of the k8s Secret to be created
  data:
  - secretKey: tls.crt
    remoteRef:
      key: ci-distro-ultrawombat-com
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: ci-distro-ultrawombat-com
      property: tls.key

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: camunda-helm-existing-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: distribution-team
  target:
    name: integration-test  # name of the k8s Secret to be created
  data:
  - secretKey: client-secret
    remoteRef:
      key: integration-test
      property: client-secret
  - secretKey: identity-firstuser-password
    remoteRef:
      key: integration-test
      property: identity-firstuser-password
  - secretKey: operate-secret
    remoteRef:
      key: integration-test
      property: operate-secret
  - secretKey: tasklist-secret
    remoteRef:
      key: integration-test
      property: tasklist-secret
  - secretKey: optimize-secret
    remoteRef:
      key: integration-test
      property: optimize-secret
  - secretKey: connectors-secret
    remoteRef:
      key: integration-test
      property: connectors-secret
  - secretKey: console-secret
    remoteRef:
      key: integration-test
      property: console-secret
  - secretKey: keycloak-secret
    remoteRef:
      key: integration-test
      property: keycloak-secret
  - secretKey: zeebe-secret
    remoteRef:
      key: integration-test
      property: zeebe-secret
  - secretKey: admin-password
    remoteRef:
      key: integration-test
      property: admin-password
  - secretKey: management-password
    remoteRef:
      key: integration-test
      property: management-password
  - secretKey: postgres-password
    remoteRef:
      key: integration-test
      property: postgres-password
  - secretKey: password
    remoteRef:
      key: integration-test
      property: password
  - secretKey: smtp-password
    remoteRef:
      key: integration-test
      property: smtp-password
        
