{{- if .Values.executionIdentity.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "executionIdentity.fullname" . }}-configuration
  labels:
    {{- include "executionIdentity.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if .Values.executionIdentity.configuration }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.executionIdentity.configuration "context" $ ) | nindent 4 }}
    {{- else }}
    # https://docs.camunda.io/docs/self-managed/executionIdentity-deployment/configuration/
    camunda:
      executionIdentity:
        oAuth:
          audience: {{ .Values.global.identity.auth.executionIdentity.audience | quote }}
          clientId: {{ .Values.global.identity.auth.executionIdentity.clientId | quote }}
          issuer: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
          jwksUri: {{ include "camundaPlatform.authIssuerBackendUrlCertsEndpoint" . | quote }}
          type: {{ include "camundaPlatform.authType" . | quote }}
          wellKnown: {{ .Values.global.identity.auth.executionIdentity.wellKnown | quote }}
        managed:
          method: plain
          releases:
            {{- include "camundaPlatform.releaseInfo" . | nindent 10 }}
    {{- end }}
{{- end }}
