{{- if .Values.executionIdentity.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "executionIdentity.fullname" . }}-configuration
  labels:
    {{- include "executionIdentity.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if .Values.executionIdentity.configuration }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.executionIdentity.configuration "context" $ ) | nindent 4 }}
    {{- else }}
    {{- end }}

    spring:
      profiles:
        active: "identity,auth-basic"

    # Camunda Database configuration
    {{- if .Values.global.elasticsearch.enabled }}
    camunda.database:
      type: elasticsearch
      # Cluster name
      clusterName: {{ .Values.global.elasticsearch.clusterName }}
      {{- if .Values.global.elasticsearch.external }}
      username: {{ .Values.global.elasticsearch.auth.username | quote }}
      {{- end }}
      # Elasticsearch full url
      url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
    {{- end }}

    zeebe:
      gateway:
        cluster:
          initial-contact-points: zeebe:26502
          member-id: identity
{{- end }}