kind: ConfigMap
metadata:
  name: {{ include "zeebe.fullname" . }}
  labels: {{- include "zeebe.labels.broker" . | nindent 4 }}
apiVersion: v1
data:
  startup.sh: |
    #!/usr/bin/env bash
    set -eux -o pipefail
{{- if eq .Values.global.installationType "failOver" }}
    export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-$[${K8S_NAME##*-} * 2 * {{.Values.global.regions}} + {{.Values.global.regionId}}]}
{{- else }}
    export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-$[${K8S_NAME##*-} * {{.Values.global.regions}} + {{.Values.global.regionId}}]}
{{- end }}

    if [ "$(ls -A /exporters/)" ]; then
      mkdir /usr/local/zeebe/exporters/
      cp -a /exporters/*.jar /usr/local/zeebe/exporters/
    else
      echo "No exporters available."
    fi

    export ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
    export ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_ARGS_URL=http://elasticsearch-master.europe-west1-b.svc.cluster.local:9200
    export ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH2_ARGS_BULK_SIZE=1

    {{- if .Values.debug }}
    env
    {{- end }}
    
{{- if eq .Values.global.installationType "failBack" }}
    if [ $[${K8S_NAME##*-} % 2] -eq 0 ]
    then
      trap : TERM INT; sleep infinity & wait
    else
      exec /usr/local/zeebe/bin/broker
    fi
{{- else }}
    exec /usr/local/zeebe/bin/broker
{{- end }}

  broker-log4j2.xml: |
{{- if .Values.log4j2 }}
    {{ .Values.log4j2 | indent 4 | trim }}
{{- end }}
