# Default values for ccsm-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Annotations to apply to all deployments
annotations: {}
labels:
  app: zeebe

global:
  elasticsearch:
    url:
    host: "elasticsearch-master"
    port: 9200
  ccsm: "{{ .Release.Name }}-ccsm"

image:
  repository: camunda/zeebe
  tag: 1.3.1
  pullPolicy: IfNotPresent
  pullSecrets: []

zeebe:
  #############
  # CONFIGS
  #############
  clusterSize: "3"
  partitionCount: "3"
  replicationFactor: "3"

  env: []
  logLevel: info
  JavaOpts: >-
    -XX:MaxRAMPercentage=25.0
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/local/zeebe/data
    -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
    -XX:+ExitOnOutOfMemoryError
  probePath: /ready

  #############
  # SERVICE
  #############
  serviceType: ClusterIP
  serviceHttpPort: 9600
  serviceCommandPort: 26501
  serviceInternalPort: 26502

  #############
  # RESOURCES
  #############
  cpuThreadCount: "2"
  ioThreadCount: "2"

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi

  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]

  extraVolumes: {}
  extraVolumeMounts: {}
  #############
  # POD
  #############
  podDisruptionBudget:
    enabled: false
    minAvailable:
    maxUnavailable: 1

  podSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  priorityClassName: ""

  readinessProbe:
    failureThreshold: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  #############
  # GATEWAY
  #############
  gateway:
    annotations: {}
    replicas: 1
    logLevel: info
    env: []
    podDisruptionBudget:
      enabled: false
      minAvailable: 1
      maxUnavailable:
    priorityClassName: ""
    resources:  {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    serviceGatewayType: ClusterIP
    serviceGatewayPort: 26500
    serviceAccount:
      create: true
      name: ""
      annotations: {}

elasticsearch:
  enabled: true
  imageTag: 7.16.2

kibana:
  enabled: false
  imageTag: 7.16.2

prometheus:
  enabled: false
  servicemonitor:
    enabled: false

serviceAccount:
  create: true
  name: ""
  annotations: {}