{{- if .Values.zeebe.enabled -}}
kind: ConfigMap
metadata:
  name: {{ include "zeebe.fullname.borker" . }}
  labels:
    {{- include "zeebe.labels.broker" . | nindent 4 }}
apiVersion: v1
data:
  startup.sh: |
    #!/usr/bin/env bash
    set -eux -o pipefail

    export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_NAME##*-}}

    if [ "$(ls -A /exporters/)" ]; then
      mkdir /usr/local/zeebe/exporters/
      cp -a /exporters/*.jar /usr/local/zeebe/exporters/
    else
      echo "No exporters available."
    fi

    {{- if .Values.zeebe.debug }}

    env
    {{- end }}

    exec /usr/local/zeebe/bin/broker

  broker-log4j2.xml: |
{{- if .Values.zeebe.log4j2 }}
    {{ .Values.zeebe.log4j2 | indent 4 | trim }}
{{- end }}
{{- end }}
