
{{- if .Values.global.createGlobalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: identity-secret-for-components
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
type: Opaque
data:
  operate-secret:  {{ randAlphaNum 12 | b64enc | quote }}
  tasklist-secret:  {{ randAlphaNum 12 | b64enc | quote }}
  optimize-secret:  {{ randAlphaNum 12 | b64enc | quote }}
  connectors-secret:  {{ randAlphaNum 12 | b64enc | quote }}
  console-secret:  {{ randAlphaNum 12 | b64enc | quote }}
  keycloak-secret:  {{ randAlphaNum 12 | b64enc | quote }}
  zeebe-secret:  {{ randAlphaNum 12 | b64enc | quote }}
  admin-password:  {{ randAlphaNum 12 | b64enc | quote }} # used for keycloak
  management-password:  {{ randAlphaNum 12 | b64enc | quote }} # used for keycloak
  postgres-password:  {{ randAlphaNum 12 | b64enc | quote }} # used for postgresql admin password
  password:  {{ randAlphaNum 12 | b64enc | quote }} # used for postgresql user password
{{- end }}
