name: Venom Deploy TestSuite
description: Deploy named Venom TestSuite
inputs:
  kubernetes-namespace:
    description: ""
    required: true
  testsuite-base-path:
    description: ""
    required: true
  testsuite-prefix:
    description: ""
    default: integration-venom
  testsuite-id:
    description: ""
    required: true
  testsuite-timeout:
    description: ""
    default: 3m
runs:
  using: "composite"
  steps:
  - name: Run TestSuite
    shell: bash
    run: |
      # Vars.
      TEST_NAMESPACE=${{ inputs.kubernetes-namespace }}
      TEST_ID=${{ inputs.testsuite-id }}
      TEST_PATH=${{ inputs.testsuite-base-path }}/$TEST_ID
      TEST_NAME=${{ inputs.testsuite-prefix }}-$TEST_ID
      TEST_TIMEOUT=${{ inputs.testsuite-timeout }}

      # Deploy.
      kubectl kustomize $TEST_PATH | kubectl apply -n $TEST_NAMESPACE -f -

      # Get logs.
      while [[ ! $(kubectl logs -n $TEST_NAMESPACE job/$TEST_NAME 2> /dev/null) ]]; do
          echo "Waiting for the test Pod to start ...";
          sleep 5;
      done
      kubectl logs -n $TEST_NAMESPACE --follow job/$TEST_NAME

      # Check status.
      kubectl wait -n $TEST_NAMESPACE --for=condition=Complete job/$TEST_NAME --timeout=$TEST_TIMEOUT
