---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store-token-auth
spec:
  provider:
    kubernetes:
      remoteNamespace: distribution-team
      server:
        url: REPLACE_ME # the url will be dynamically replaced in .github/workflows/test-integration-rosa.yaml using `yq`
        caProvider:
          type: Secret
          name: "external-clusters-access-secret-store-token"
          key: "ca.crt"
          namespace: distribution-team
      auth:
        token:
          bearerToken:
            name: "external-clusters-access-secret-store-token"
            key: "token"
