{{- if .Values.core.enabled -}}
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}-configuration
  labels:
    {{- include "core.labels" . | nindent 4 }}
apiVersion: v1
data:
  startup.sh: |
    # The Node ID depends on the Pod name so it cannot be templated in the StatefulSet level.
    export ZEEBE_BROKER_CLUSTER_NODEID="${ZEEBE_BROKER_CLUSTER_NODEID:-$[${K8S_NAME##*-} * 1 + 0]}"
    echo "export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID}" >> ~/.bashrc

    exec /usr/local/camunda/bin/camunda

  {{- if .Values.core.configuration }}
  application.yaml: |
    {{ .Values.core.configuration | indent 4 | trim }}
  {{- else }}
  application.yaml: |
    {{ if .Values.global.identity.auth.enabled }}
    spring:
      profiles:
        active: "identity,operate,tasklist,broker,auth-oidc"
      security:
        oauth2:
          client:
            provider:
              oidcclient:
                {{- $issuerURIDefault := (include "camundaPlatform.authIssuerBackendUrl" . | replace ":80" "") }}
                issuer-uri: {{ (include "camundaPlatform.authIssuerUrl" .) | default $issuerURIDefault | quote }}
            registration:
              oidcclient:
                client-id: {{ include "core.authClientId" . | quote }}
                client-secret: ${VALUES_CAMUNDA_CORE_CLIENT_SECRET:}
                # authorization-grant-type: authorization_code
                {{- $redirectURIDefault := printf "http://%s:8080" (include "core.fullname" .) }}
                redirect-uri: "{{ tpl .Values.global.identity.auth.core.redirectUrl $ | default $redirectURIDefault }}/login/oauth2/code/core"
                provider: oidcclient
                scope: openid,profile

    {{- else }}
    spring:
      profiles:
        active: auth
    {{- end }}

    management:
      server:
        port: {{ .Values.core.service.managementPort }}
        {{- if .Values.core.contextPath }}
        base-path: {{ .Values.core.contextPath | quote }}
        {{- end }}

    server:
      forward-headers-strategy: framework
      address: 0.0.0.0
      port: {{ .Values.core.service.httpPort }}
      {{- if .Values.core.contextPath }}
      servlet:
        context-path: {{ .Values.core.contextPath | quote }}
      {{- end }}

    zeebe:
      host: 0.0.0.0
      log:
        level: {{ .Values.core.logLevel | quote }}

      broker:
        # zeebe.broker.experimental
        experimental:
          engine:
            authorization:
              enableAuthorization: true

        # zeebe.broker.gateway
        gateway:
          enable: true
          network:
            host: 0.0.0.0
            port: {{ .Values.core.service.grpcPort }}
          {{- if .Values.global.multitenancy.enabled }}
          multitenancy:
            enabled: true
          {{- end }}

        # zeebe.broker.network
        network:
          {{- if gt (int .Values.global.multiregion.regions) 1 }}
          advertisedHost: "${K8S_NAME}.${K8S_SERVICE_NAME}.${K8S_NAMESPACE}.svc"
          {{- else }}
          advertisedHost: "${K8S_NAME}.${K8S_SERVICE_NAME}"
          {{- end }}
          host: 0.0.0.0
          commandApi:
            port: {{ .Values.core.service.commandPort }}
          internalApi:
            port: {{ .Values.core.service.internalPort }}

        # zeebe.broker.cluster
        cluster:
          initialContactPoints:
          {{- range (untilStep 0 (int .Values.core.clusterSize) 1) }}
            - ${K8S_SERVICE_NAME}-{{ . }}.${K8S_SERVICE_NAME}:{{$.Values.core.service.internalPort}}
          {{- end }}
          clusterSize: {{ .Values.core.clusterSize | quote }}
          replicationFactor: {{ .Values.core.replicationFactor | quote }}
          partitionsCount: {{ .Values.core.partitionCount | quote }}
          clusterName: {{ tpl .Values.global.zeebeClusterName . }}

        # zeebe.broker.data
        data:
          snapshotPeriod: 5m
          freeSpace:
            processing: 2GB
            replication: 3GB

        # zeebe.broker.threads
        threads:
          cpuThreadCount: {{ .Values.core.cpuThreadCount  | quote }}
          ioThreadCount: {{ .Values.core.ioThreadCount  | quote }}

        # zeebe.broker.exporters
        exporters:
        {{- if and (not .Values.global.elasticsearch.disableExporter) .Values.global.elasticsearch.enabled }}
          elasticsearch:
            className: "io.camunda.zeebe.exporter.ElasticsearchExporter"
            args:
              {{- if .Values.global.elasticsearch.external }}
              authentication:
                username: {{ .Values.global.elasticsearch.auth.username | quote }}
              {{- end }}
              url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
              index:
                prefix: {{ .Values.global.elasticsearch.prefix | quote }}
              {{- if .Values.core.retention.enabled }}
              retention:
                enabled: true
                minimumAge: {{ .Values.core.retention.minimumAge | quote }}
                policyName: {{ .Values.core.retention.policyName | quote }}
              {{- end }}
        {{- else if .Values.global.opensearch.enabled }}
          opensearch:
            className: "io.camunda.zeebe.exporter.opensearch.OpensearchExporter"
            args:
              url: {{ include "camundaPlatform.opensearchURL" . | quote }}
              {{- if .Values.global.opensearch.auth.username }}
              authentication:
                username: {{ .Values.global.opensearch.auth.username | quote }}
              {{- end }}
              {{- if .Values.global.opensearch.aws.enabled }}
              aws:
                enabled: true
              {{- end}}
              {{- if .Values.core.retention.enabled }}
              retention:
                enabled: true
                minimumAge: {{ .Values.core.retention.minimumAge | quote }}
                policyName: {{ .Values.core.retention.policyName | quote }}
              {{- end }}
          {{- end }}
        {{- if or .Values.global.elasticsearch.enabled .Values.global.opensearch.enabled }}
          CamundaExporter:
            className: "io.camunda.exporter.CamundaExporter"
            args:
              connect:
                type: {{ if .Values.global.elasticsearch.enabled }}elasticsearch{{ else }}opensearch{{ end }}
                url: {{ if .Values.global.elasticsearch.enabled }}{{ include "camundaPlatform.elasticsearchURL" . | quote }}{{ else }}{{ include "camundaPlatform.opensearchURL" . | quote }}{{- end }}
              {{- if or .Values.global.elasticsearch.auth.username .Values.global.opensearch.auth.username }}
                username: {{ if .Values.global.elasticsearch.auth.username }}{{ .Values.global.elasticsearch.auth.username | quote }}{{ else }}{{ .Values.global.opensearch.auth.username | quote }}{{- end }}
              {{- end }}
              {{- if .Values.core.retention.enabled }}
              retention:
                enabled: true
                minimumAge: {{ .Values.core.retention.minimumAge | quote }}
                policyName: {{ .Values.core.retention.policyName | quote }}
              {{- end }}
              createSchema: true
        {{- else -}}
          {{ " {}" }}
        {{- end }}

    camunda:
      rest:
        query:
          enabled: true

      {{- if .Values.global.identity.auth.enabled }}
      identity:
        clientId: {{ include "core.authClientId" . | quote }}
        audience: {{ include "core.authAudience" . | quote }}
      {{- end }}

      #
      # Camunda Database Configuration.
      #
      {{- if .Values.global.elasticsearch.enabled }}
      database:
        type: elasticsearch
        # Cluster name
        clusterName: {{ .Values.global.elasticsearch.clusterName }}
        {{- if .Values.global.elasticsearch.external }}
        username: {{ .Values.global.elasticsearch.auth.username | quote }}
        {{- end }}
        # Elasticsearch full url
        url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
      {{- end }}
      {{- if .Values.global.opensearch.enabled }}
      database:
        type: opensearch
        url: {{ include "camundaPlatform.opensearchURL" . | quote }}
        {{- if .Values.global.opensearch.auth.username }}
        username: {{ .Values.global.opensearch.auth.username | quote }}
        {{- end }}
      {{- end }}

      #
      # Camunda Operate Configuration.
      #
      operate:
        {{- if .Values.global.opensearch.enabled }}
        database: opensearch
        {{- end }}
        {{- if .Values.global.multitenancy.enabled }}
        multiTenancy:
          enabled: true
        {{- end }}
        {{- if .Values.global.identity.auth.enabled }}
        identity:
          redirectRootUrl: "{{ tpl .Values.global.identity.auth.core.redirectUrl $ }}/operate"
        {{- end }}
      
        # ELS instance to store Operate data
        {{- if .Values.global.elasticsearch.enabled }}
        elasticsearch:
          # Cluster name
          clusterName: {{ .Values.global.elasticsearch.clusterName }}
          {{- if .Values.global.elasticsearch.external }}
          username: {{ .Values.global.elasticsearch.auth.username | quote }}
          {{- end }}
          # Host
          host: {{ include "camundaPlatform.elasticsearchHost" . }}
          # Transport port
          port: {{ .Values.global.elasticsearch.url.port }}
          {{- if .Values.global.elasticsearch.url.host }}
          # Elasticsearch full url
          url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
          {{- end }}
        # ELS instance to export Zeebe data to
        zeebeElasticsearch:
          # Cluster name
          clusterName: {{ .Values.global.elasticsearch.clusterName }}
          # Host
          host: {{ include "camundaPlatform.elasticsearchHost" . }}
          # Transport port
          port: {{ .Values.global.elasticsearch.url.port }}
          # Index prefix, configured in Zeebe Elasticsearch exporter
          prefix: {{ .Values.global.elasticsearch.prefix }}
          {{- if .Values.global.elasticsearch.url.host }}
          # Elasticsearch full url
          url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
          {{- end }}
          {{- if .Values.global.elasticsearch.external }}
          # Elasticsearch username
          username: {{ .Values.global.elasticsearch.auth.username | quote }}
          {{- end }}
        {{- end }}
        # Zeebe instance
        zeebe:
          # Gateway address
          gatewayAddress: "{{ include "core.fullname" . }}:{{ .Values.core.service.grpcPort }}"
        {{- if .Values.global.opensearch.enabled }}
        opensearch:
          url: {{ include "camundaPlatform.opensearchURL" . | quote }}
          {{- if .Values.global.opensearch.aws.enabled }}
          awsEnabled: true
          {{- end }}
          {{- if .Values.global.opensearch.auth.username }}
          username: {{ .Values.global.opensearch.auth.username | quote }}
          {{- end }}
        zeebeOpensearch:
          url: {{ include "camundaPlatform.opensearchURL" . | quote }}
          {{- if .Values.global.opensearch.auth.username }}
          username: {{ .Values.global.opensearch.auth.username | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.core.retention.enabled }}
        archiver:
          ilmEnabled: true
          ilmMinAgeForDeleteArchivedIndices: {{ .Values.core.retention.minimumAge }}
        {{- end }}

      #
      # Camunda Tasklist Configuration.
      #
      tasklist:
        {{- if .Values.global.multitenancy.enabled }}
        multiTenancy:
          enabled: true
        {{- end }}

        identity:
          redirectRootUrl: "{{ tpl .Values.global.identity.auth.core.redirectUrl $ }}/tasklist"

        # Set Tasklist username and password.
        # If user with <username> does not exists it will be created.
        # Default: demo/demo
        #username:
        #password:
        {{- if .Values.global.elasticsearch.enabled }}
        # ELS instance to store Tasklist data
        elasticsearch:
          # Cluster name
          clusterName: {{ .Values.global.elasticsearch.clusterName }}
          # Host
          host: {{ include "camundaPlatform.elasticsearchHost" . }}
          # Transport port
          port: {{ .Values.global.elasticsearch.url.port }}
          {{- if .Values.global.elasticsearch.url.host }}
          # Elasticsearch full url
          url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
          {{- end }}
          {{- if .Values.global.elasticsearch.external }}
          username: {{ .Values.global.elasticsearch.auth.username | quote }}
          {{- end }}
        # ELS instance to export Zeebe data to
        zeebeElasticsearch:
          # Cluster name
          clusterName: {{ .Values.global.elasticsearch.clusterName }}
          # Host
          host: {{ include "camundaPlatform.elasticsearchHost" . }}
          # Transport port
          port: {{ .Values.global.elasticsearch.url.port }}
          # Index prefix, configured in Zeebe Elasticsearch exporter
          prefix: {{ .Values.global.elasticsearch.prefix }}
          {{- if .Values.global.elasticsearch.url.host }}
          # Elasticsearch full url
          url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
          {{- end }}
          {{- if .Values.global.elasticsearch.external }}
          username: {{ .Values.global.elasticsearch.auth.username | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.global.opensearch.enabled }}
        database: opensearch
        opensearch:
          url: {{ include "camundaPlatform.opensearchURL" . | quote }}
          {{- if .Values.global.opensearch.aws.enabled }}
          awsEnabled: true
          {{- end }}
          {{- if .Values.global.opensearch.auth.username }}
          username: {{ .Values.global.opensearch.auth.username | quote }}
          {{- end }}
        zeebeOpensearch:
          url: {{ include "camundaPlatform.opensearchURL" . | quote }}
          {{- if .Values.global.opensearch.auth.username }}
          username: {{ .Values.global.opensearch.auth.username | quote }}
          {{- end }}
        {{- end }}
        # Zeebe instance
        zeebe:
          # Gateway address
          gatewayAddress: {{ include "core.fullname" . }}:{{ .Values.core.service.grpcPort }}
          restAddress: {{ include "camundaPlatform.zeebeGatewayRESTURL" . | quote }}
        {{- if .Values.core.retention.enabled }}
        archiver:
          ilmEnabled: true
          ilmMinAgeForDeleteArchivedIndices: {{ .Values.core.retention.minimumAge }}
        {{- end }}

    {{- end }}

  log4j2.xml: |
  {{- if .Values.core.log4j2 }}
    {{ .Values.core.log4j2 | indent 4 | trim }}
  {{- end }}

  {{- range $key, $val := .Values.core.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
