{{- if .Values.core.enabled -}}
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}-configuration
  labels:
    {{- include "core.labels" . | nindent 4 }}
apiVersion: v1
data:
  {{- if .Values.core.configuration }}
  application.yaml: |
    {{ .Values.core.configuration | indent 4 | trim }}
  {{- else }}
  application.yaml: |
    zeebe:
      broker:
        exporters:
        {{- if and (not .Values.global.elasticsearch.disableExporter) .Values.global.elasticsearch.enabled }}
          elasticsearch:
            className: "io.camunda.core.exporter.ElasticsearchExporter"
            args:
              {{- if .Values.global.elasticsearch.external }}
              authentication:
                username: {{ .Values.global.elasticsearch.auth.username | quote }}
              {{- end }}
              url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
              index:
                prefix: {{ .Values.global.elasticsearch.prefix | quote }}
              {{- if .Values.core.retention.enabled }}
              retention:
                enabled: true
                minimumAge: {{ .Values.core.retention.minimumAge | quote }}
                policyName: {{ .Values.core.retention.policyName | quote }}
              {{- end }}
        {{- else if .Values.global.opensearch.enabled }}
          opensearch:
            className: "io.camunda.core.exporter.opensearch.OpensearchExporter"
            args:
              url: {{ include "camundaPlatform.opensearchURL" . | quote }}
              {{- if .Values.global.opensearch.auth.username }}
              authentication:
                username: {{ .Values.global.opensearch.auth.username | quote }}
              {{- end }}
              {{- if .Values.global.opensearch.aws.enabled }}
              aws:
                enabled: true
              {{- end}}
              {{- if .Values.core.retention.enabled }}
              retention:
                enabled: true
                minimumAge: {{ .Values.core.retention.minimumAge | quote }}
                policyName: {{ .Values.core.retention.policyName | quote }}
              {{- end }}
          {{- end }}
        {{- if or .Values.global.elasticsearch.enabled .Values.global.opensearch.enabled }}
          CamundaExporter:
            className: "io.camunda.exporter.CamundaExporter"
            args:
              connect:
                type: {{ if .Values.global.elasticsearch.enabled }}elasticsearch{{ else }}opensearch{{ end }}
                url: {{ if .Values.global.elasticsearch.enabled }}{{ include "camundaPlatform.elasticsearchURL" . | quote }}{{ else }}{{ include "camundaPlatform.opensearchURL" . | quote }}{{- end }}
              {{- if or .Values.global.elasticsearch.auth.username .Values.global.opensearch.auth.username }}
                username: {{ if .Values.global.elasticsearch.auth.username }}{{ .Values.global.elasticsearch.auth.username | quote }}{{ else }}{{ .Values.global.opensearch.auth.username | quote }}{{- end }}
              {{- end }}
              {{- if .Values.core.retention.enabled }}
              retention:
                enabled: true
                minimumAge: {{ .Values.core.retention.minimumAge | quote }}
                policyName: {{ .Values.core.retention.policyName | quote }}
              {{- end }}
              createSchema: true
        {{- else -}}
          {{ " {}" }}
        {{- end }}
        gateway:
          enable: true
          network:
            port: 26500
          security:
            enabled: false
            authentication:
              mode: none
        network:
          host: 0.0.0.0
          commandApi:
            port: {{ .Values.core.service.commandPort }}
          internalApi:
            port: {{ .Values.core.service.internalPort }}
          monitoringApi:
            port: {{  .Values.core.service.httpPort | quote }}
        cluster:
          clusterSize: {{ .Values.core.clusterSize | quote }}
          replicationFactor: {{ .Values.core.replicationFactor | quote }}
          partitionsCount: {{ .Values.core.partitionCount | quote }}
          clusterName: {{ tpl .Values.global.zeebeClusterName . }}
        threads:
          cpuThreadCount: {{ .Values.core.cpuThreadCount  | quote }}
          ioThreadCount: {{ .Values.core.ioThreadCount  | quote }}

    # Camunda Database configuration
    {{- if .Values.global.elasticsearch.enabled }}
    camunda.database:
      type: elasticsearch
      # Cluster name
      clusterName: {{ .Values.global.elasticsearch.clusterName }}
      {{- if .Values.global.elasticsearch.external }}
      username: {{ .Values.global.elasticsearch.auth.username | quote }}
      {{- end }}
      # Elasticsearch full url
      url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
    {{- end }}
    {{- if .Values.global.opensearch.enabled }}
    camunda.database:
      type: opensearch
      url: {{ include "camundaPlatform.opensearchURL" . | quote }}
      {{- if .Values.global.opensearch.auth.username }}
      username: {{ .Values.global.opensearch.auth.username | quote }}
      {{- end }}
    {{- end }}
  {{- end }}

  startup.sh: |
    #!/usr/bin/env bash
    set -eux -o pipefail
    
{{- if eq .Values.global.multiregion.installationType "failOver" }}
    export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-$[${K8S_NAME##*-} * 2 * {{.Values.global.multiregion.regions}} + {{.Values.global.multiregion.regionId}}]}
{{- else }}
    export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-$[${K8S_NAME##*-} * {{.Values.global.multiregion.regions}} + {{.Values.global.multiregion.regionId}}]}
{{- end }}

    if [ "$(ls -A /exporters/)" ]; then
      mkdir -p /usr/local/camunda/exporters/
      cp -a /exporters/*.jar /usr/local/camunda/exporters/
    else
      echo "No exporters available."
    fi

    {{- if .Values.core.debug }}

    env
    {{- end }}
{{- if eq .Values.global.multiregion.installationType "failBack" }}
    if [ $[${K8S_NAME##*-} % 2] -eq 0 ]
    then
      trap : TERM INT; sleep infinity & wait
    else
      exec /usr/local/camunda/bin/broker
    fi
{{- else }}
    exec /usr/local/camunda/bin/broker
{{- end }}

  broker-log4j2.xml: |
  {{- if .Values.core.log4j2 }}
    {{ .Values.core.log4j2 | indent 4 | trim }}
  {{- end }}

  {{- range $key, $val := .Values.core.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
