{{- if .Values.operate.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operate.fullname" . }}
  labels:
    {{- include "operate.labels" . | nindent 4 }}
data:
  {{- if .Values.operate.configuration }}
  application.yml: |
    {{ .Values.operate.configuration | indent 4 | trim }}
  {{- else }}
  application.yml: |
    {{- if .Values.operate.contextPath }}
    server:
      servlet:
        context-path: {{ .Values.operate.contextPath | quote }}
    {{- end }}
    {{- if .Values.global.identity.auth.enabled }}
    spring:
      profiles:
        active: "identity-auth"
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
              jwk-set-uri: {{ include "camundaPlatform.authIssuerBackendUrlCertsEndpoint" . | quote }}

    camunda:
      identity:
        clientId: {{ include "operate.authClientId" . | quote }}
        audience: {{ include "operate.authAudience" . | quote }}
    {{- else }}
    spring:
      profiles:
        active: "auth"
    {{- end }}
    
    # Operate configuration file
    camunda.operate:
      {{- if .Values.global.multitenancy.enabled }}
      multiTenancy:
        enabled: true
      {{- end }}
      {{- if .Values.global.identity.auth.enabled }}
      identity:
        redirectRootUrl: {{ tpl .Values.global.identity.auth.operate.redirectUrl $ | trimSuffix .Values.operate.contextPath | quote }}
      {{- end }}
    
      # ELS instance to store Operate data
      elasticsearch:
        # Cluster name
        clusterName: {{ .Values.global.elasticsearch.clusterName }}
        # Host
        host: {{ include "camundaPlatform.elasticsearchHost" . }}
        # Transport port
        port: {{ .Values.global.elasticsearch.url.port }}
      # Zeebe instance
      zeebe:
        # Broker contact point
        brokerContactPoint: "{{ tpl .Values.global.zeebeClusterName . }}-gateway:{{ .Values.global.zeebePort }}"
      # ELS instance to export Zeebe data to
      zeebeElasticsearch:
        # Cluster name
        clusterName: {{ .Values.global.elasticsearch.clusterName }}
        # Host
        host: {{ include "camundaPlatform.elasticsearchHost" . }}
        # Transport port
        port: {{ .Values.global.elasticsearch.url.port }}
        # Index prefix, configured in Zeebe Elasticsearch exporter
        prefix: {{ .Values.global.elasticsearch.prefix }}
      {{- if .Values.operate.retention.enabled }}
      archiver:
        ilmEnabled: true
        ilmMinAgeForDeleteArchivedIndices: {{ .Values.operate.retention.minimumAge }}
      {{- end }}
    logging:
{{- with .Values.operate.logging }}
{{ . | toYaml | indent 6 }}
{{- end }}
    #Spring Boot Actuator endpoints to be exposed
    management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus,loggers,usage-metrics,backups
  {{- end }}

  {{- range $key, $val := .Values.operate.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
