{{- if .Values.operate.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operate.fullname" . }}
  labels:
    {{- include "operate.labels" . | nindent 4 }}
data:
  application.yml: |
    # Operate configuration file
    camunda.operate:
      # ELS instance to store Operate data
      elasticsearch:
        # Cluster name
        clusterName: {{ .Values.global.elasticsearch.clusterName }}
        # Host
        host: {{ include "camundaPlatform.elasticsearchHost" . }}
        # Transport port
        port: {{ .Values.global.elasticsearch.url.port }}
      # Zeebe instance
      zeebe:
        # Broker contact point
        brokerContactPoint: "{{ tpl .Values.global.zeebeClusterName . }}-gateway:{{ .Values.global.zeebePort }}"
      # ELS instance to export Zeebe data to
      zeebeElasticsearch:
        # Cluster name
        clusterName: {{ .Values.global.elasticsearch.clusterName }}
        # Host
        host: {{ include "camundaPlatform.elasticsearchHost" . }}
        # Transport port
        port: {{ .Values.global.elasticsearch.url.port }}
        # Index prefix, configured in Zeebe Elasticsearch exporter
        prefix: {{ .Values.global.elasticsearch.prefix }}
      {{- if .Values.operate.retention.enabled }}
      archiver:
        ilmEnabled: true
        ilmMinAgeForDeleteArchivedIndices: {{ .Values.operate.retention.minimumAge }}
      {{- end }}
    logging:
{{- with .Values.operate.logging }}
{{ . | toYaml | indent 6 }}
{{- end }}
    #Spring Boot Actuator endpoints to be exposed
    management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus,loggers,usage-metrics,backups
{{- end }}
