apiVersion: v2
name: camunda-platform
version: 8.6.0-alpha4
appVersion: 8.6.x
description: |
  Camunda 8 Self-Managed Helm charts.
  Camunda's process automation platform allows developers to design, automate and improve processes.
type: application
icon: https://helm.camunda.io/imgs/camunda.svg
home: https://docs.camunda.io/docs/self-managed/overview/
sources:
  - https://github.com/camunda/camunda-platform-helm
keywords:
  - bpm
  - bpmn
  - camunda-platform
  - dmn
  - process-engine
  - workflow
dependencies:
  # Identity Dependencies.
  - name: keycloak
    alias: identityKeycloak
    repository: https://charts.bitnami.com/bitnami
    version: 22.1.2
    condition: "identity.keycloak.enabled,identityKeycloak.enabled"
  - name: postgresql
    alias: identityPostgresql
    repository: https://charts.bitnami.com/bitnami
    version: 14.x.x
    condition: "identity.postgresql.enabled,identityPostgresql.enabled"
  # WebModeler Dependencies.
  - name: web-modeler-postgresql
    alias: postgresql
    repository: "file://../web-modeler-postgresql-14"
    version: 14.x.x
    condition: "postgresql.enabled"
  # Shared Dependencies.
  - name: elasticsearch
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 20.0.4
    condition: "elasticsearch.enabled"
  # Helpers.
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
  - name: aabouzaid
    email: ahmed.abouzaid@camunda.com
annotations:
  camunda.io/helmCLIVersion: "3.15.3"
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: "Add volumeClaimTemplates label selector in zeebe statefulSet"
    - kind: added
      description: "Support migration init container for operate"
    - kind: added
      description: "Configure camunda database to be used by v2 API"
    - kind: changed
      description: "Hardcoding strategy for all components and removing ability to configure strategy"
    - kind: fixed
      description: "Changed restAddress in Tasklist with helper function"
    - kind: fixed
      description: "Template grpc url in console config"
    - kind: fixed
      description: "Set the network host and port to the zeebeGateway config"
    - kind: fixed
      description: "Add constraint for contextPath and rest path to be the same for zeebe gateway"
    - kind: fixed
      description: "Use correct operate image for version label"
    - kind: fixed
      description: "Drop namespace from zeebe advertisedHost and initialContactPoints"
    - kind: fixed
      description: "ExistingSecret for OpenSearch password can be used without defining password literal"
