{{- if .Values.connectors.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connectors.fullname" . }}-configuration
  labels:
    {{- include "connectors.labels" . | nindent 4 }}
data:
  {{- if .Values.connectors.configuration }}
  application.yml: |
    {{ .Values.connectors.configuration | indent 4 | trim }}
  {{- else }}
  application.yml: |
    server:
      port: {{ .Values.connectors.service.serverPort }}
    {{- if .Values.connectors.contextPath }}
      servlet:
        context-path: {{ .Values.connectors.contextPath | quote }}
    {{- end }}

    management:
      endpoints:
        web:
          exposure:
            include: metrics,health,prometheus
      endpoint:
        health:
          show-details: always
          show-components: always
          group:
            readiness:
              include:
              - zeebeClient
              - operate
      context-path: /actuator

    camunda:
      client:
        zeebe:
          defaults:
            worker-threads: 10
            max-jobs-active: 32
            stream-enabled: true
          gateway-url: http://{{ include "core.fullname" . }}:{{ .Values.core.service.grpcPort }}
        identity:
          base-url: {{ include "camundaPlatform.identityURL" . | quote }}
          audience: {{ include "core.authAudience" . | quote }}
        operate:
          base-url: http://{{ include "core.fullname" . }}:{{ .Values.core.service.grpcPort }}{{ .Values.core.contextPath }}/v1
        auth:
          issuer: {{ include "camundaPlatform.authIssuerUrl" . }}
          client-id: {{ include "connectors.authClientId" . | quote }}
          client-secret: ${VALUES_CAMUNDA_IDENTITY_CLIENT_SECRET}
          oidc-type: keycloak
        mode: {{ include "connectors.operateClientProfile" . }}

    logging:
{{- with .Values.connectors.logging }}
{{ . | toYaml | indent 6 }}
{{- end }}
  {{- range $key, $val := .Values.connectors.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
{{- end }}
