apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Description: this is a template cluster that is used each time we spawn an "on-demand" ROSA HCP cluster in the CI
#              it extends the default configuration of the generic on-demand ROSA cluster with specific values set by the workflow

commonAnnotations:
  camunda.com/team: distribution

commonLabels:
  app.kubernetes.io/managed-by: kustomize

resources:
- ./external-dns
- ./distribution-team
