{{- if .Values.webModeler.enabled -}}
{{- $useExternalDatabasePassword := and (not .Values.postgresql.enabled) (or (not .Values.webModeler.restapi.externalDatabase.existingSecret) (typeIs "string" .Values.webModeler.restapi.externalDatabase.existingSecret)) }}
{{- $useSmtpPassword := and (not .Values.webModeler.restapi.mail.existingSecret) .Values.webModeler.restapi.mail.smtpPassword }}
{{- if or $useExternalDatabasePassword $useSmtpPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webModeler.restapi.fullname" . }}
  labels: {{- include "webModeler.restapi.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  {{- if $useExternalDatabasePassword }}
  database-password: {{ .Values.webModeler.restapi.externalDatabase.existingSecret | b64enc }}
  {{- end }}
  {{- if $useSmtpPassword }}
  smtp-password: {{ .Values.webModeler.restapi.mail.smtpPassword | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
