{{- if and (.Values.connectors.enabled) (eq .Values.connectors.inbound.mode "oauth") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connectors.fullname" . }}
  labels: {{- include "connectors.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if and .Values.connectors.inbound.keycloak.existingSecret .Values.connectors.inbound.keycloak.existingSecret.keycloakConnectorsClientId }}
  keycloakConnectorsClientId: {{ .Values.connectors.inbound.keycloak.existingSecret.keycloakConnectorsClientId }}
  {{ else }}
  keycloakConnectorsClientId: connectors
  {{ end }}
  {{ if and .Values.connectors.inbound.keycloak.existingSecret .Values.connectors.inbound.keycloak.existingSecret.keycloakConnectorsSecret }}
  keycloakConnectorsClientSecret: {{ .Values.connectors.inbound.keycloak.existingSecret.keycloakConnectorsSecret }}
  {{ else }}
  keycloakConnectorsClientSecret: c0nn3ct0rsAr3Aw3s0me
  {{ end }}
{{ end }}