{{- if .Values.connectors.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "connectors.fullname" . }}
  labels: {{- include "connectors.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.connectors.service.annotations}}
    {{- toYaml .Values.connectors.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.connectors.service.type }}
  ports:
    - name: http
      port: {{ .Values.connectors.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "connectors.matchLabels" . | nindent 4 }}
{{- end }}