name: Cat File from PR

on:
  pull_request_target:
    types: [opened, edited]
jobs:
  cat-file:
    runs-on: ubuntu-latest

    steps:
    - name: Generate GitHub token
      uses: tibdex/github-app-token@v2
      id: generate-github-token
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        token: '${{ steps.generate-github-token.outputs.token }}'
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Cat file
      run: |
        cat path/to/your/file.txt