# Copy files to the gh-pages branch to have clean and shorter links.
# Example: https://helm.camunda.io/camunda-platform/values/values-latest.yaml
name: "Chart - Public Files"

on:
  push:
    branches:
    - main
    paths:
    - 'charts/camunda-platform/values/*.yaml'
    - 'charts/camunda-platform/VERSION-MATRIX.md'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  copy-values-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: gh-pages
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: main
      - name: Copy the values files
        run: |
          mkdir -p camunda-platform/values camunda-platform/version-matrix
          cp -a main/charts/camunda-platform/values/*.yaml camunda-platform/values/
          cp -a main/charts/camunda-platform/VERSION-MATRIX.md camunda-platform/version-matrix/README.md
          rm -rf main
          find .
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          message: "chore: update camunda-platform public files"
