name: Cat File from PR

on:
  pull_request_target:
    types: [opened, edited]
  pull_request:
    paths:
      - '**/*'
  push:
    paths:
      - '**/*'
jobs:
  cat-file:
    runs-on: ubuntu-latest

    steps:
      - name: echo message
        run: echo "hello from hamza"
      - name: Generate GitHub token
        uses: tibdex/github-app-token@v2
        id: generate-github-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: '${{ steps.generate-github-token.outputs.token }}'
      - name: cat file
        run: cat charts/camunda-platform/values.yaml