name: Cat File from PR

on:
  pull_request_target:
    types: [opened, edited]
  pull_request:
    paths:
      - '**/*'
jobs:
  cat-file:
    runs-on: ubuntu-latest

    steps:
      - name: echo message
        run: echo "hello from hamza"