name: "Chart - Update README"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/camunda-platform*/README.md'
      - 'charts/camunda-platform*/values.yaml'
      - '.github/workflows/chart-update-readme.yaml'

permissions:
  contents: read

jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Generate GitHub token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-github-token
        with:
          app_id: ${{ secrets.GH_APP_ID_DISTRO_CI }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI }}
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          token: '${{ steps.generate-github-token.outputs.token }}'
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm
      - name: Run readme generator
        run: |
          echo "Updating README.md"
          make helm.readme-update
          git diff --exit-code || (
            echo "Please ensure to run: make helm.readme-update";
            exit 1;
          )
