name: "Chart - Validate"

on:
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/**'
      - '.tool-versions'
      - 'charts/camunda-platform*/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/chart-validate-template.yaml
    with:
      identifier: "${{ github.event.pull_request.number }}"
      camunda-helm-git-ref: "${{ github.event.pull_request.head.sha }}"
