name: "Chart - Update Golden Files and README"

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/chart-update-readme-and-golden-files.yaml"
      - "charts/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  init:
    # The workflow shouldn't run on renovatebot branches, we have another workflow for renovatebot.
    if: ${{ !contains(github.head_ref, 'renovate/') }} ||
        ${{ !contains(github.head_ref, 'release-please--') }}
    name: Check conditions
    runs-on: ubuntu-latest
    steps:
      - name: Conditions met
        run: |
          echo "Conditions met, move to the next job..."
    
  chores:
    needs: [init]
    name: Update README And Golden Files
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout.
      #
      - name: Generate GitHub token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-github-token
        with:
          app_id: ${{ secrets.GH_APP_ID_DISTRO_CI }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI }}
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: "${{ steps.generate-github-token.outputs.token }}"
      #
      # Dependencies.
      #
      - name: Install dependencies
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
      - name: Install readme-generator-for-helm
        run: |
          npm install -g @bitnami/readme-generator-for-helm
      - name: Add Helm repos
        run: |
          make helm.repos-add
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.asdf/installs/golang/*/packages/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      #
      # Update
      #
      - name: Set vars
        run: |
          echo "CHANGED_CHARTS=$(ct list-changed | tr '\n' ' ')" | tee -a $GITHUB_ENV
      - name: Update golden files
        run: |
          chartPath="${CHANGED_CHARTS}" \
            make go.update-golden-only
      - name: Update README
        run: |
          chartPath="${CHANGED_CHARTS}" \
            make helm.readme-update
      - name: Git pull
        run: git pull --rebase --autostash .
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          author_name: "distro-ci[bot]"
          author_email: "122795778+distro-ci[bot]@users.noreply.github.com"
          message: "chore: Update golden files"
