name: "Chart - Update README"

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'charts/camunda-platform/values.yaml'
jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub token
        uses: tibdex/github-app-token@v2
        id: generate-github-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          token: '${{ steps.generate-github-token.outputs.token }}'
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm
      - name: Run readme generator
        run: |
          echo "Updating README.md"
          make helm.readme-update
      - uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: "renovate[bot]"
          author_email: "29139614+renovate[bot]@users.noreply.github.com"
          message: "chore: Update README.md using readme-generator-for-helm"
