name: "Chart - Update README"

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/chart-update-readme.yaml'
      - 'charts/camunda-platform*/README.md'
      - 'charts/camunda-platform*/values.yaml'

permissions:
  contents: read

jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Generate GitHub token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-github-token
        with:
          app_id: ${{ secrets.GH_APP_ID_DISTRO_CI }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          token: '${{ steps.generate-github-token.outputs.token }}'
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm
      - name: Run readme generator
        run: |
          echo "Updating README.md"
          chartPath="$(ct list-changed | tr '\n' ' ')" \
            make helm.readme-update
          git diff --exit-code || (
            echo "Please ensure to run: make helm.readme-update";
            exit 1;
          )
