name: "Chart - Release - Candidate"

on:
  workflow_dispatch:
    inputs:
      update-branch:
        type: boolean
        default: false
      camunda-version:
        type: choice
        description: Camunda version in form of x.y, alpha, or alpha-8.8.
        options:
          - "8.3"
          - "8.4"
          - "8.5"
          - "8.6"
          - "alpha"
          - "alpha-8.8"

jobs:
  reset:
    name: Reset Branch
    if: inputs.update-branch
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: main
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Update RC branch from main
        run: |
          git checkout -b release-candidate
          git push --force --set-upstream origin release-candidate

  release:
    name: Release
    if: inputs.camunda-version
    uses: ./.github/workflows/chart-release-template.yaml
    with:
      branch: release-candidate
      workflow-ref: chart-release-template.yaml
      chart-matrix: |
        [
          {
            "name": "Helm Chart ${{ inputs.camunda-version }}",
            "directory": "charts/camunda-platform-${{ inputs.camunda-version }}",
            "versionSuffix": "rc-${{ inputs.camunda-version }}",
            "override": true
          }
        ]
