name: "Chart - Release - Snapshot"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/chart-release-snapshot.yaml
      - charts/camunda-platform-alpha/*
      - charts/camunda-platform-8.6/*

jobs:
  release:
    name: Release Candidate
    uses: ./.github/workflows/chart-release-template.yaml
    with:
      branch: ${{ github.ref_name }}
      workflow-ref: chart-release-template.yaml
      chart-matrix: |
        [
          {
            "name": "Helm Chart rolling - Latest",
            "directory": "charts/camunda-platform-8.6",
            "versionSuffix": "snapshot-latest",
            "override": true
          },
          {
            "name": "Helm Chart rolling - Alpha",
            "directory": "charts/camunda-platform-alpha",
            "versionSuffix": "snapshot-alpha",
            "override": true
          },
          {
            "name": "Helm Chart versioned - Alpha",
            "directory": "charts/camunda-platform-alpha",
            "versionSuffix": "",
            "override": false
          }
        ]
