name: "Dispatch - Integration - Main"

on:
  workflow_dispatch:
    inputs:
      identifier:
        description: The unique identifier of used in the deployment hostname.
        required: true
        type: string
      git-ref:
        description: Git ref
        required: false
        default: main
        type: string
      persistent:
        description: |
          Keep test deployment after the workflow is done.
          NOTE: All persistent deployments will be deleted frequently to save costs!
        required: false
        default: false
        type: boolean
      platforms:
        description: platforms
        default: gke
        type: string
      flows:
        description: flows
        required: false
        default: install
        type: string
      test-enabled:
        description: test enabled
        required: false
        default: true
        type: boolean
      extra-values:
        description: Pass extra values to the Helm chart.
        required: false
        type: string
jobs:
  helm-deploy:
    name: Helm chart Integration Tests
    uses: ./.github/workflows/test-integration-template.yaml
    secrets: inherit
    with:
      identifier: ${{ github.event.inputs.identifier }}
      git-ref: ${{ github.event.inputs.git-ref }}
      persistent: ${{ github.event.inputs.persistent == 'true' }}
      platforms: ${{ github.event.inputs.platforms }}
      flows: ${{ github.event.inputs.flows }}
      test-enabled: ${{ github.event.inputs.test-enabled == 'true' }}
      extra-values: ${{ github.event.inputs.extra-values }}
