name: Openshift Integration Tests

on:
  pull_request:
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  workflow_dispatch: { }

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  build:
    if: github.ref == 'refs/heads/main' || github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      matrix:
        include:
          - version: "4.10"
            server: OPENSHIFT_URL_410
            token: OPENSHIFT_TOKEN_410
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: asdf-vm/actions/install@v1
      - name: Install Openshift client (oc)
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: ${{ matrix.version }}
      - name: Authenticate to Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets[matrix.server] }}
          openshift_token: ${{ secrets[matrix.token] }}
      # the tests need to be able to create a project and list nodes; node listing is to find an available pod when
      # checking service availability (done via terratest, so we cannot change that)
      - name: 'Verify Permissions'
        run: 'oc auth can-i create projectrequests && oc auth can-i list nodes'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Add helm repos
        run: |
          make helm-repos-add
      - name: Run tests
        run: make it-os

