name: Go CI

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Format
      run: |
        make fmt
        diff=$(git status --porcelain)
        if [ -n "$diff" ]
        then
          echo "Some files are not following the go format ($diff), run gofmt and fix your files."
          exit 1
        fi
    - name: Install License Tool
      run: make installLicense
    - name: Check License
      run: make checkLicense
    - name: Install Helm
      uses: asdf-vm/actions/install@v1
    - name: Add helm repos
      run: |
        make helm-repos-add
    - name: Get Helm dependency
      run: make helm-dependency-update
    - name: Test
      run: make test
