name: Renovate - Config Check

on:
  pull_request:
    paths:
    - '.github/renovate.json5'
  workflow_dispatch: { }

jobs:
  check:
    name: Check renovate config 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Validate renovate config
      uses: docker://renovate/renovate
      with:
        args: renovate-config-validator
