# Mimic postUpgradeTasks which is only available for self-hosted Renovate instances.
# https://docs.renovatebot.com/configuration-options/#postupgradetasks
name: Renovate - Post Upgrade Tasks

on:
  push:
    branches:
    - 'renovate/*'
    paths:
    - 'charts/camunda-platform/values.yaml'
    - 'charts/camunda-platform/templates/**'
    - 'charts/camunda-platform/charts/**'

jobs:
  run:
    name: Update golden files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: asdf-vm/actions/setup@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Update golden files
      run: make go.test-golden-updated
    - uses: EndBug/add-and-commit@v9.1.3
      with:
        author_name: "renovate[bot]"
        author_email: "29139614+renovate[bot]@users.noreply.github.com"
        message: "chore(deps): Running post upgrade tasks"
