name: Renovate - Config Check

on:
  pull_request:
    paths:
    - '.github/renovate.json5'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  check:
    name: Check renovate config 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
    - name: Validate renovate config
      uses: docker://renovate/renovate
      with:
        args: renovate-config-validator
