name: Repo - Issue Labels

on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write
  contents: read

jobs:
  issue-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue Labeler
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          configuration-path: .github/config/issue-labeler.yaml
          enable-versioned-regex: 0
          repo-token: "${{ github.token }}"
