name: "Test - Integration - ROSA"

# description: This workflow perform integration tests against ROSA platform, it only prepares the cluster to run the tests

on:
  schedule:
    - cron: '0 3 * * 1,3,5' # Runs at 3 AM on Monday, Wednesday, and Friday
  pull_request:
    paths:
      - '.github/workflows/configs/test-integration-rosa-matrix.yaml'
      - '.github/workflows/test-integration-rosa.yaml'
      - '.github/actions/workflow-vars/**'
      - '.github/actions/test-type-vars/**'

permissions:
  contents: read

jobs:
  test:
    name: Main
    permissions:
      contents: read
      id-token: write
      deployments: write
    secrets: inherit
    uses: ./.github/workflows/test-integration-rosa-template.yaml
    with:
      deployment-ttl: "${{ contains(github.event.pull_request.labels.*.name, 'test-persistent') && '1d' || '' }}"
      caller-git-ref: ${{ github.event.pull_request.head.sha }}
      camunda-helm-git-ref: ${{ github.event.pull_request.head.sha }}
