# TODO: Later we should move to Testkube.
# https://github.com/kubeshop/testkube
name: "Test - Integration - Kubernetes"

on:
  pull_request:
    types:
    - labeled
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger release manually'
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CAMUNDA_DISTRO_TEST_DELETE_NAMESPACE: ${{ !secrets.ACTIONS_STEP_DEBUG }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  GITHUB_WORKFLOW_RUN_ID: ${{ github.run_id }}
  KUBECONFIG: .github/config/kubeconfig
  TEST_SCENARIOS_DIR: charts/camunda-platform/test/integration/scenarios
  TEST_CLUSTER_TYPE: kubernetes
  TEST_CREATE_DOCKER_LOGIN_SECRET: "TRUE"
  TEST_DOCKER_USERNAME: ${{ secrets.TEST_DOCKER_USERNAME }}
  TEST_DOCKER_PASSWORD: ${{ secrets.TEST_DOCKER_PASSWORD }}
  # This is needed to access WebModeler Docker image since it's not public.
  TEST_DOCKER_USERNAME_CAMUNDA_CLOUD: ${{ secrets.CAMUNDA_REGISTRY_USER }}
  TEST_DOCKER_PASSWORD_CAMUNDA_CLOUD: ${{ secrets.CAMUNDA_REGISTRY_PASSWORD }}

jobs:
  test:
    name: ${{ matrix.test.title }}
    if: ${{ contains(github.event.*.labels.*.name, 'test-integration-extra') || github.event.inputs.trigger }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        test:
        - title: ChartWithDefaultValues
          dir: chart-with-default-values
          description: Test Camunda Platform Helm chart default values
        - title: ChartUpgrade
          dir: chart-upgrade
          description: Test Camunda Platform Helm chart upgrade
        - title: ChartWithCustomValues
          dir: chart-with-custom-values
          description: Test Camunda Platform Helm chart custom values
        - title: ChartWithWebModeler
          dir: chart-with-web-modeler
          description: Test Camunda Platform Helm chart with WebModeler enabled which is still beta
    steps:
    - uses: actions/checkout@v3
    - name: Login to GKE
      uses: ./.github/actions/gke-login
      with:
        cluster-name: ${{ secrets.GKE_CLUSTER }}
        cluster-location: ${{ secrets.GKE_ZONE }}
        workload-identity-provider: ${{ secrets.GCP_AUTH_WORKLOAD_IDENTITY_PROVIDER }}
        service-account: ${{ secrets.GCP_AUTH_SERVICE_ACCOUNT }}
    - name: Set PR vars
      uses: ./.github/actions/pr-vars
    - name: Install env dependencies
      uses: asdf-vm/actions/install@v2
    - name: Add Helm repos and dependencies
      run: |
        make helm.repos-add
        make helm.dependency-update
    - name: Create test namespace
      run: |
        kubectl create ns $TEST_NAMESPACE
        kubectl label ns $TEST_NAMESPACE github-run-id=$GITHUB_WORKFLOW_RUN_ID
        kubectl label ns $TEST_NAMESPACE github-job-id=$GITHUB_WORKFLOW_JOB_ID
    - name: Pre setup
      timeout-minutes: 5
      run: |
        task -d $TEST_SCENARIOS_DIR/${{ matrix.test.dir }} setup.pre
    - name: Setup Camunda Platform
      run: |
        task -d $TEST_SCENARIOS_DIR/${{ matrix.test.dir }} setup.exec
    - name: Post setup
      timeout-minutes: 5
      run: |
        task -d $TEST_SCENARIOS_DIR/${{ matrix.test.dir }} setup.post
    - name: ⭐️ Run Preflight TestSuite ⭐️
      timeout-minutes: 10
      run: |
        task -d $TEST_SCENARIOS_DIR/${{ matrix.test.dir }} test.preflight
    - name: ⭐️ Run Core TestSuite ⭐️
      timeout-minutes: 20
      run: |
        task -d $TEST_SCENARIOS_DIR/${{ matrix.test.dir }} test.core
    - name: Get failed Pods info
      if: failure()
      uses: ./.github/actions/failed-pods-info
    - name: Cleanup test namespace
      if: always() && env.CAMUNDA_DISTRO_TEST_DELETE_NAMESPACE != 'false'
      run: |
        kubectl delete ns \
          --ignore-not-found=true \
          -l github-run-id=$GITHUB_WORKFLOW_RUN_ID \
          -l github-job-id=$GITHUB_WORKFLOW_JOB_ID
