name: "Test - Integration"

on:
  pull_request:
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  workflow_dispatch: { }

env:
  KUBECTL_VERSION: 'latest'
  KUBECTX: 'gke_zeebe-io_europe-west1-b_zeebe-cluster'
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  GITHUB_WORKFLOW_RUN_ID: ${{ github.run_id }}

jobs:
  test:
    name: ${{ matrix.test.name }}
    if: github.ref == 'refs/heads/main' || github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      fail-fast: false
      matrix:
        test:
        - name: "End2End"
          method: "TestServicesEnd2End"
        - name: "End2EndShouldFailWithUpgrade"
          method: "TestServicesEnd2EndShouldFailWithUpgrade"
        - name: "End2EndWithUpgrade"
          method: "TestServicesEnd2EndWithUpgrade"
        - name: "End2EndWithConfig"
          method: "TestServicesEnd2EndWithConfig"
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: .github/config/kubeconfig
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Set var GITHUB_PR_HEAD_SHA_SHORT
      run: echo "GITHUB_PR_HEAD_SHA_SHORT=$(echo $GITHUB_PR_HEAD_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/helm-identity-pool/providers/helm-identity-provider'
        service_account: 'camunda-platform-helm@zeebe-io.iam.gserviceaccount.com'
    - id: 'get-credentials'
      name: 'Get GKE credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: 'zeebe-cluster'
        location: 'europe-west1-b'
    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: 'check-credentials'
      name: 'Check credentials'
      run: 'kubectl auth can-i create deployment'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install Helm
      uses: asdf-vm/actions/install@v1
    - name: Add helm repos
      run: make helm.repos-add
    - name: Test - ${{ matrix.test.name }}
      run: make go.test-it GO_TEST_IT_ARGS="-testify.m ${{ matrix.test.method }}"
