# Docs: https://github.com/camunda/camunda-platform-helm/blob/main/docs/gha-workflows.md
name: "Test - Integration - Template"

on:
  workflow_call:
    inputs:
      identifier:
        description: The unique identifier of used in the deployment hostname.
        required: true
        type: string
      camunda-helm-git-ref:
        required: false
        default: main
        type: string
      caller-git-ref:
        required: false
        default: main
        type: string
      persistent:
        description: |
          Keep test deployment after the workflow is done.
          NOTE: All persistent deployments will be deleted frequently to save costs!
        required: false
        default: false
        type: boolean
      platforms:
        default: gke
        type: string
      flows:
        required: false
        default: install
        type: string
      test-enabled:
        required: false
        default: true
        type: boolean
      extra-values:
        description: Pass extra values to the Helm chart.
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.identifier }}
  cancel-in-progress: true

env:
  TEST_PERSISTENT: ${{ inputs.persistent }}
  TEST_IDENTIFIER: ${{ inputs.identifier }}
  TEST_HOSTNAME_BASE: ci.distro.ultrawombat.com
  TEST_SCENARIOS_DIR: charts/camunda-platform/test/integration/scenarios
  # Docker Hub auth to avoid image pull rate limit.
  TEST_CREATE_DOCKER_LOGIN_SECRET: "TRUE"
  TEST_DOCKER_USERNAME: ${{ secrets.DISTRO_CI_DOCKER_USERNAME_DOCKERHUB }}
  TEST_DOCKER_PASSWORD: ${{ secrets.DISTRO_CI_DOCKER_PASSWORD_DOCKERHUB }}
  # Camunda registry auth to access WebModeler Docker image since it's not public.
  TEST_DOCKER_USERNAME_CAMUNDA_CLOUD: ${{ secrets.DISTRO_CI_DOCKER_USERNAME_CAMUNDA }}
  TEST_DOCKER_PASSWORD_CAMUNDA_CLOUD: ${{ secrets.DISTRO_CI_DOCKER_PASSWORD_CAMUNDA }}

permissions:
  contents: read
  
jobs:
  test:
    name: ${{ matrix.distro.name }} - ${{ matrix.scenario.name }}
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    strategy:
      fail-fast: false
      matrix:
        distro:
        - name: Kubernetes 1.27
          type: kubernetes
          platform: gke
          secret:
            cluster-name: DISTRO_CI_GCP_GKE_CLUSTER_NAME
            cluster-location: DISTRO_CI_GCP_GKE_CLUSTER_LOCATION
            workload-identity-provider: DISTRO_CI_GCP_WORKLOAD_IDENTITY_PROVIDER
            service-account: DISTRO_CI_GCP_SERVICE_ACCOUNT
          if: ${{ contains(inputs.platforms, 'gke') }}
        - name: OpenShift 4.14
          type: openshift
          version: 4.14
          platform: rosa
          secret:
            server-url: DISTRO_CI_OPENSHIFT_CLUSTER_URL
            username: DISTRO_CI_OPENSHIFT_CLUSTER_USERNAME
            password: DISTRO_CI_OPENSHIFT_CLUSTER_PASSWORD
          if: ${{ contains(inputs.platforms, 'rosa') }}
        scenario:
        - name: Chart Setup
          desc: Setup chart in production-like setup with Ingress and TLS.
          flow: install
          if: ${{ contains(inputs.flows, 'install') }}
        - name: Chart Upgrade
          desc: Upgrade chart from the latest released version to the current branch.
          flow: upgrade
          if: ${{ contains(inputs.flows, 'upgrade') }}
        exclude:
        - distro:
            if: false
        - scenario:
            if: false
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      with:
        # This is needed to load repo GH composite actions if the workflow triggered by workflow_call.
        repository: camunda/camunda-platform-helm
        ref: ${{ inputs.camunda-helm-git-ref }}

    # TODO: Later, find a way to abstract the auth for different platforms.
    - name: Authenticate to GKE
      if: matrix.distro.platform == 'gke'
      uses: ./.github/actions/gke-login
      with:
        cluster-name: ${{ secrets[matrix.distro.secret.cluster-name] }}
        cluster-location: ${{ secrets[matrix.distro.secret.cluster-location] }}
        workload-identity-provider: ${{ secrets[matrix.distro.secret.workload-identity-provider] }}
        service-account: ${{ secrets[matrix.distro.secret.service-account] }}
    
    - name: Authenticate to OpenShift
      if: matrix.distro.platform == 'rosa'
      uses: redhat-actions/oc-login@5eb45e848b168b6bf6b8fe7f1561003c12e3c99d # v1
      with:
        openshift_server_url: ${{ secrets[matrix.distro.secret.server-url] }}
        openshift_username: ${{ secrets[matrix.distro.secret.username] }}
        openshift_password: ${{ secrets[matrix.distro.secret.password] }}

    - name: Ensure identifier is set
      run: |
        if [ -z "${{ env.TEST_IDENTIFIER }}" ]; then
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "TEST_IDENTIFIER=$calculatedSha" >> $GITHUB_ENV
        fi

    - name: Launch tests
      uses: ./.github/actions/chart-test-recipes
      with:
        platform: "${{ matrix.distro.platform }}"
        type: "${{ matrix.distro.type }}"

        identifier: "${{ env.TEST_IDENTIFIER }}"
        persistent: "${{ env.TEST_PERSISTENT }}"
        flow: "${{ matrix.scenario.flow }}"
        test-enabled: "${{ inputs.test-enabled }}"

        caller-git-ref: ${{ inputs.caller-git-ref  }}
        extra-values: ${{ inputs.extra-values }}
        ingress-hostname-base: ${{ env.TEST_HOSTNAME_BASE }}

        gh_app_id: ${{ secrets.GH_APP_ID_DISTRO_CI_MANAGE_GH_ENVS }}
        gh_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI_MANAGE_GH_ENVS }}

  clean:
    name: Clean up persistent resources
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    # Used to create/delete GitHub environment.
    # NOTE: The GH app requires "administration:write" access to be able to delete the GH environment.
    - name: Generate GitHub token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
      id: generate-github-token
      with:
        app_id: ${{ secrets.GH_APP_ID_DISTRO_CI_MANAGE_GH_ENVS }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI_MANAGE_GH_ENVS }}
    - name: Set PR vars
      id: vars
      uses: ./.github/actions/workflow-vars
      with:
        persistent: ${{ env.TEST_PERSISTENT }}
        platform: gke
        identifier-base: ${{ inputs.identifier }}
    # Persistent resources are deployed only on GKE.
    - name: Authenticate to GKE
      uses: ./.github/actions/gke-login
      with:
        cluster-name: ${{ secrets.DISTRO_CI_GCP_GKE_CLUSTER_NAME }}
        cluster-location: ${{ secrets.DISTRO_CI_GCP_GKE_CLUSTER_LOCATION }}
        workload-identity-provider: ${{ secrets.DISTRO_CI_GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service-account: ${{ secrets.DISTRO_CI_GCP_SERVICE_ACCOUNT }}
    - name: Cleanup GitHub deployment
      if: always()
      uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8 # v1
      with:
        step: delete-env
        token: ${{ steps.generate-github-token.outputs.token }}
        env: ${{ steps.vars.outputs.identifier }}
        ref: ${{ inputs.caller-git-ref }}
    - name: Cleanup test namespace
      if: always()
      run: |
        kubectl delete ns --ignore-not-found=true \
          -l "github-id=${{ steps.vars.outputs.identifier }},test-persistent=true"