name: "Test - Unit"

on:
  push:
    branches:
    - main
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  pull_request:
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  workflow_dispatch: { }

jobs:
  test:
    name: Custom values - ${{ matrix.test.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
        - name: Core
          packages: camunda identity
        - name: Apps
          packages: connectors operate optimize tasklist
        - name: Zeebe
          packages: zeebe zeebe-gateway
        - name: WebModeler
          packages: web-modeler
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Install env dependencies
      uses: asdf-vm/actions/install@v3
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Format
      run: make go.fmt
    - name: Install License Tool
      run: |
        make go.addlicense-install
        asdf reshim golang
    - name: Check License
      run: make go.addlicense-check
    - name: Add helm repos
      run: make helm.repos-add
    - name: Get Helm dependency
      run: make helm.dependency-update
    - name: ⭐️ Test ⭐️
      run: |
        cd charts/camunda-platform/test/unit
        go test $(printf "./%s " ${{ matrix.test.packages }})
