name: 'Update README'

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'charts/camunda-platform/values.yaml'
jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm
      - name: Checkout bitnami/charts
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          path: charts
          ref: ${{github.event.pull_request.head.ref}}
          repository: camunda/camunda-platform-helm
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute readme-generator-for-helm
        run: |
            echo "Updating README.md"
            readme-generator --values "charts/camunda-platform/values.yaml" --readme "charts/camunda-platform/README.md"
      - name: Push changes
        run: |
            git add . && git commit -am "Update README.md with readme-generator-for-helm" --signoff && git push