name: "Chart - Update Golden Files"

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/update-goldenfiles.yaml"
      - "charts/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  chores:
    name: Update Golden Files
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout.
      #
      - name: Set vars
        run: |
          echo "CHANGED_CHARTS=$(ct list-changed | tr '\n' ' ')" | tee -a $GITHUB_ENV
      - name: Generate GitHub token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-github-token
        with:
          app_id: ${{ secrets.GH_APP_ID_DISTRO_CI }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI }}
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      #
      # Update
      #
      - name: Update golden files
        run: |
          chartPath="${CHANGED_CHARTS}" \
            make go.update-golden-only
      - name: Git pull
        run: git pull --rebase --autostash .
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          author_name: "distro-ci[bot]"
          author_email: "122795778+distro-ci[bot]@users.noreply.github.com"
          message: "chore: Update golden files"
